import { getSupabasePublicClient } from "@/lib/supabasePublicClient";

function normalizeRecipeRow(row) {
  return {
    id: row.id,
    title: row.title,
    cuisine: row.cuisine,
    protein: row.protein,
    sauce: row.sauce,
    garnish: row.garnish,
    matchType: row.match_type,
    servings: row.servings,
    ingredients: row.ingredients ?? [],
    steps: row.steps ?? [],
    source: row.source ?? {},
  };
}

export async function getRecipeById(id) {
  const supabase = getSupabasePublicClient();
  const { data, error } = await supabase.from("recipes").select("*").eq("id", id).maybeSingle();
  if (error) throw new Error(error.message);
  return data ? normalizeRecipeRow(data) : null;
}

export async function getRecipesByIds(ids) {
  if (!ids.length) return [];
  const supabase = getSupabasePublicClient();
  const { data, error } = await supabase.from("recipes").select("*").in("id", ids);
  if (error) throw new Error(error.message);
  return (data ?? []).map(normalizeRecipeRow);
}

// Distinct cuisines present in the catalog, for the Dish Passport's "still
// to discover" teaser — sorted alphabetically, "Unknown"/empty excluded.
export async function getCatalogCuisines() {
  const supabase = getSupabasePublicClient();
  const { data, error } = await supabase.from("recipes").select("cuisine");
  if (error) throw new Error(error.message);

  const cuisines = new Set(
    (data ?? [])
      .map((row) => row.cuisine?.trim())
      .filter((cuisine) => cuisine && cuisine.toLowerCase() !== "unknown")
  );
  return [...cuisines].sort((a, b) => a.localeCompare(b));
}

// Inserts a Gemini-generated recipe under a caller-chosen id, unless a
// recipe with that id already exists (e.g. from a previous "Cook me"
// click on the same scan) — in which case it's reused as-is. Storing the
// embedding (when one was computed) lets this recipe surface for someone
// else's similar scan via /api/match-recipes, instead of only ever being
// reachable through this one scan's id. `sourceExtra` merges into the
// `source` column — used to record remix provenance (remixOf/remixLabel)
// without a schema migration.
export async function saveAiGeneratedRecipe(id, recipe, embedding, sourceExtra) {
  const existing = await getRecipeById(id);
  if (existing) return existing;

  const supabase = getSupabasePublicClient();
  const { error } = await supabase.from("recipes").insert({
    id,
    title: recipe.title,
    cuisine: recipe.cuisine,
    protein: recipe.protein,
    sauce: recipe.sauce,
    garnish: recipe.garnish,
    match_type: "ai-generated",
    servings: recipe.servings,
    ingredients: recipe.ingredients,
    steps: recipe.steps,
    source: { name: "AI-generated by Abracadish", ...sourceExtra },
    embedding: embedding ?? null,
  });
  if (error) {
    console.error("Saving AI-generated recipe failed:", error);
    throw new Error("Couldn't save this recipe. Please try again.");
  }

  console.log(`[Abracadish] New recipe added to catalog: "${recipe.title}" (${id})`);

  return getRecipeById(id);
}
