import { getSupabaseClient } from "@/lib/supabaseClient";

function normalizeRecipeRow(row) {
  return {
    id: row.id,
    title: row.title,
    cuisine: row.cuisine,
    protein: row.protein,
    sauce: row.sauce,
    garnish: row.garnish,
    matchType: row.match_type,
    servings: row.servings,
    ingredients: row.ingredients ?? [],
    steps: row.steps ?? [],
    source: row.source ?? {},
  };
}

export async function getRecipeById(id) {
  const supabase = getSupabaseClient();
  const { data, error } = await supabase.from("recipes").select("*").eq("id", id).maybeSingle();
  if (error) throw new Error(error.message);
  return data ? normalizeRecipeRow(data) : null;
}

export async function getRecipesByIds(ids) {
  if (!ids.length) return [];
  const supabase = getSupabaseClient();
  const { data, error } = await supabase.from("recipes").select("*").in("id", ids);
  if (error) throw new Error(error.message);
  return (data ?? []).map(normalizeRecipeRow);
}

// Inserts a Gemini-generated recipe under a caller-chosen id, unless a
// recipe with that id already exists (e.g. from a previous "Cook this dish"
// click on the same scan) — in which case it's reused as-is.
export async function saveAiGeneratedRecipe(id, recipe) {
  const existing = await getRecipeById(id);
  if (existing) return existing;

  const supabase = getSupabaseClient();
  const { error } = await supabase.from("recipes").insert({
    id,
    title: recipe.title,
    cuisine: recipe.cuisine,
    protein: recipe.protein,
    sauce: recipe.sauce,
    garnish: recipe.garnish,
    match_type: "ai-generated",
    servings: recipe.servings,
    ingredients: recipe.ingredients,
    steps: recipe.steps,
    source: { name: "AI-generated by Abracadish" },
  });
  if (error) throw new Error(error.message);

  return getRecipeById(id);
}
