// One-off script: embeds and upserts the starter recipe catalog into Supabase.
// Run manually with: node scripts/seed-recipes.mjs
// Uses SUPABASE_SERVICE_ROLE_KEY directly (bypasses RLS) — never import this
// file from application code.

import { createClient } from "@supabase/supabase-js";
import { buildRecipeEmbeddingText } from "../lib/recipeMatch.js";

process.loadEnvFile(".env.local");

const RECIPES = [
  {
    id: "ctm-classic",
    title: "Classic Chicken Tikka Masala",
    matchType: "likely",
    cuisine: "Indian",
    protein: "Chicken",
    sauce: "Creamy tomato",
    garnish: "Cilantro",
    servings: 4,
    ingredients: [
      { name: "Chicken thigh, diced", quantity: 600, unit: "g" },
      { name: "Plain yogurt", quantity: 200, unit: "g" },
      { name: "Onion, diced", quantity: 1, unit: "" },
      { name: "Garlic, minced", quantity: 3, unit: "cloves" },
      { name: "Ginger, grated", quantity: 1, unit: "tbsp" },
      { name: "Crushed tomatoes", quantity: 400, unit: "g" },
      { name: "Heavy cream", quantity: 120, unit: "ml" },
      { name: "Garam masala", quantity: 2, unit: "tsp" },
      { name: "Olive oil", quantity: 2, unit: "tbsp" },
      { name: "Cilantro, chopped", quantity: 2, unit: "tbsp" },
    ],
    steps: [
      { text: "Dice the onion.", timerMinutes: null },
      { text: "Heat 2 tbsp olive oil in a pan.", timerMinutes: null },
      { text: "Marinate the chicken in yogurt and half the garam masala for 15 minutes.", timerMinutes: 15 },
      { text: "Sear the marinated chicken until lightly browned, then set aside.", timerMinutes: 6 },
      { text: "In the same pan, soften the onion, garlic, and ginger.", timerMinutes: 5 },
      { text: "Add crushed tomatoes and remaining garam masala, then simmer.", timerMinutes: 10 },
      { text: "Return the chicken to the pan and stir in the cream.", timerMinutes: null },
      { text: "Simmer until the chicken is cooked through.", timerMinutes: 8 },
      { text: "Garnish with cilantro and serve.", timerMinutes: null },
    ],
    source: {
      name: "Abracadish community recipe",
      url: null,
      license: "original",
      author: "Abracadish",
      dateAdded: "2026-01-01",
    },
  },
  {
    id: "butter-chicken",
    title: "Butter Chicken",
    matchType: "similar",
    cuisine: "Indian",
    protein: "Chicken",
    sauce: "Buttery tomato",
    garnish: "Cream drizzle",
    servings: 4,
    ingredients: [
      { name: "Chicken breast, diced", quantity: 600, unit: "g" },
      { name: "Butter", quantity: 60, unit: "g" },
      { name: "Crushed tomatoes", quantity: 400, unit: "g" },
      { name: "Heavy cream", quantity: 150, unit: "ml" },
      { name: "Garam masala", quantity: 2, unit: "tsp" },
      { name: "Kashmiri chili powder", quantity: 1, unit: "tsp" },
    ],
    steps: [
      { text: "Sear the chicken in butter until golden.", timerMinutes: 6 },
      { text: "Add crushed tomatoes and spices, then simmer.", timerMinutes: 12 },
      { text: "Stir in the cream and simmer until thickened.", timerMinutes: 6 },
      { text: "Serve with a drizzle of cream.", timerMinutes: null },
    ],
    source: {
      name: "Abracadish community recipe",
      url: null,
      license: "original",
      author: "Abracadish",
      dateAdded: "2026-01-01",
    },
  },
  {
    id: "chicken-korma",
    title: "Chicken Korma",
    matchType: "similar",
    cuisine: "Indian",
    protein: "Chicken",
    sauce: "Creamy nut-based",
    garnish: "Toasted almonds",
    servings: 4,
    ingredients: [
      { name: "Chicken thigh, diced", quantity: 600, unit: "g" },
      { name: "Yogurt", quantity: 150, unit: "g" },
      { name: "Cashew paste", quantity: 60, unit: "g" },
      { name: "Onion, sliced", quantity: 1, unit: "" },
      { name: "Coriander powder", quantity: 1, unit: "tsp" },
    ],
    steps: [
      { text: "Soften the onion, then blend into a paste.", timerMinutes: 5 },
      { text: "Sear the chicken, then add the onion paste and spices.", timerMinutes: 5 },
      { text: "Stir in yogurt and cashew paste, then simmer gently.", timerMinutes: 15 },
      { text: "Garnish with toasted almonds and serve.", timerMinutes: null },
    ],
    source: {
      name: "Abracadish community recipe",
      url: null,
      license: "original",
      author: "Abracadish",
      dateAdded: "2026-01-01",
    },
  },
  {
    id: "spaghetti-carbonara",
    title: "Spaghetti Carbonara",
    matchType: "likely",
    cuisine: "Italian",
    protein: "Pork",
    sauce: "Egg and cheese",
    garnish: "Black pepper",
    servings: 4,
    ingredients: [
      { name: "Spaghetti", quantity: 400, unit: "g" },
      { name: "Pancetta or guanciale, diced", quantity: 150, unit: "g" },
      { name: "Egg yolks", quantity: 4, unit: "" },
      { name: "Whole egg", quantity: 1, unit: "" },
      { name: "Pecorino Romano, grated", quantity: 80, unit: "g" },
      { name: "Parmesan, grated", quantity: 40, unit: "g" },
      { name: "Black pepper", quantity: 1, unit: "tsp" },
    ],
    steps: [
      { text: "Bring a large pot of salted water to a boil and cook the spaghetti until al dente.", timerMinutes: 10 },
      { text: "While the pasta cooks, fry the pancetta in a dry pan until crisp.", timerMinutes: 8 },
      { text: "Whisk the egg yolks, whole egg, and grated cheeses together in a bowl.", timerMinutes: null },
      { text: "Reserve a cup of pasta water, then drain the spaghetti.", timerMinutes: null },
      { text: "Off the heat, toss the hot spaghetti with the pancetta and its fat.", timerMinutes: null },
      { text: "Quickly stir in the egg-and-cheese mixture, adding splashes of pasta water until glossy and creamy.", timerMinutes: null },
      { text: "Finish with cracked black pepper and serve immediately.", timerMinutes: null },
    ],
    source: {
      name: "Abracadish community recipe",
      url: null,
      license: "original",
      author: "Abracadish",
      dateAdded: "2026-08-23",
    },
  },
  {
    id: "margherita-pizza",
    title: "Margherita Pizza",
    matchType: "likely",
    cuisine: "Italian",
    protein: null,
    sauce: "Tomato",
    garnish: "Fresh basil",
    servings: 2,
    ingredients: [
      { name: "Pizza dough", quantity: 500, unit: "g" },
      { name: "Crushed San Marzano tomatoes", quantity: 200, unit: "g" },
      { name: "Fresh mozzarella, torn", quantity: 200, unit: "g" },
      { name: "Olive oil", quantity: 2, unit: "tbsp" },
      { name: "Garlic, minced", quantity: 1, unit: "clove" },
      { name: "Fresh basil leaves", quantity: 10, unit: "" },
      { name: "Salt", quantity: 1, unit: "tsp" },
    ],
    steps: [
      { text: "Preheat the oven (with a pizza stone if you have one) as hot as it will go.", timerMinutes: null },
      { text: "Stretch the dough into a round on a floured surface.", timerMinutes: null },
      { text: "Spread the crushed tomatoes over the dough, leaving a border for the crust.", timerMinutes: null },
      { text: "Season with salt and minced garlic.", timerMinutes: null },
      { text: "Dot the surface with torn mozzarella and drizzle with olive oil.", timerMinutes: null },
      { text: "Bake until the crust is blistered and the cheese is bubbling.", timerMinutes: 10 },
      { text: "Top with fresh basil and serve.", timerMinutes: null },
    ],
    source: {
      name: "Abracadish community recipe",
      url: null,
      license: "original",
      author: "Abracadish",
      dateAdded: "2026-08-23",
    },
  },
  {
    id: "beef-bourguignon",
    title: "Beef Bourguignon",
    matchType: "likely",
    cuisine: "French",
    protein: "Beef",
    sauce: "Red wine",
    garnish: "Parsley",
    servings: 6,
    ingredients: [
      { name: "Beef chuck, cubed", quantity: 1, unit: "kg" },
      { name: "Bacon lardons", quantity: 150, unit: "g" },
      { name: "Carrots, sliced", quantity: 2, unit: "" },
      { name: "Onion, diced", quantity: 1, unit: "" },
      { name: "Garlic, minced", quantity: 3, unit: "cloves" },
      { name: "Red wine (Burgundy)", quantity: 750, unit: "ml" },
      { name: "Beef stock", quantity: 400, unit: "ml" },
      { name: "Tomato paste", quantity: 2, unit: "tbsp" },
      { name: "Bay leaf", quantity: 1, unit: "" },
      { name: "Thyme", quantity: 1, unit: "tsp" },
      { name: "Button mushrooms", quantity: 250, unit: "g" },
      { name: "Pearl onions", quantity: 200, unit: "g" },
      { name: "Butter", quantity: 2, unit: "tbsp" },
      { name: "Flour", quantity: 2, unit: "tbsp" },
    ],
    steps: [
      { text: "Render the bacon lardons in a Dutch oven, then set aside.", timerMinutes: 5 },
      { text: "Brown the beef cubes in batches in the bacon fat.", timerMinutes: 10 },
      { text: "Soften the carrots and onion, then stir in the garlic and tomato paste.", timerMinutes: 5 },
      { text: "Sprinkle the flour over and stir to coat.", timerMinutes: null },
      { text: "Deglaze with the red wine, scraping up the browned bits.", timerMinutes: null },
      { text: "Return the beef and bacon, add the stock, bay leaf, and thyme, then cover and braise low until the beef is fork-tender.", timerMinutes: 150 },
      { text: "Sauté the mushrooms and pearl onions in butter, then stir them in.", timerMinutes: 8 },
      { text: "Garnish with parsley and serve.", timerMinutes: null },
    ],
    source: {
      name: "Abracadish community recipe",
      url: null,
      license: "original",
      author: "Abracadish",
      dateAdded: "2026-08-23",
    },
  },
  {
    id: "pad-thai",
    title: "Pad Thai",
    matchType: "likely",
    cuisine: "Thai",
    protein: "Shrimp",
    sauce: "Tamarind",
    garnish: "Crushed peanuts",
    servings: 4,
    ingredients: [
      { name: "Flat rice noodles", quantity: 250, unit: "g" },
      { name: "Shrimp, peeled", quantity: 300, unit: "g" },
      { name: "Eggs", quantity: 2, unit: "" },
      { name: "Firm tofu, cubed", quantity: 100, unit: "g" },
      { name: "Bean sprouts", quantity: 150, unit: "g" },
      { name: "Garlic chives", quantity: 1, unit: "handful" },
      { name: "Tamarind paste", quantity: 3, unit: "tbsp" },
      { name: "Fish sauce", quantity: 3, unit: "tbsp" },
      { name: "Palm sugar", quantity: 2, unit: "tbsp" },
      { name: "Garlic, minced", quantity: 2, unit: "cloves" },
      { name: "Crushed peanuts", quantity: 4, unit: "tbsp" },
      { name: "Lime wedges", quantity: 4, unit: "" },
    ],
    steps: [
      { text: "Soak the rice noodles in warm water until pliable.", timerMinutes: 20 },
      { text: "Whisk the tamarind paste, fish sauce, and palm sugar into a sauce.", timerMinutes: null },
      { text: "Stir-fry the garlic and tofu in a hot wok.", timerMinutes: 3 },
      { text: "Push everything aside, scramble the eggs, then add the shrimp.", timerMinutes: 4 },
      { text: "Add the drained noodles and sauce, tossing until coated.", timerMinutes: null },
      { text: "Fold in the bean sprouts and garlic chives.", timerMinutes: null },
      { text: "Plate and top with crushed peanuts and lime wedges.", timerMinutes: null },
    ],
    source: {
      name: "Abracadish community recipe",
      url: null,
      license: "original",
      author: "Abracadish",
      dateAdded: "2026-08-23",
    },
  },
  {
    id: "thai-green-curry",
    title: "Thai Green Curry Chicken",
    matchType: "likely",
    cuisine: "Thai",
    protein: "Chicken",
    sauce: "Coconut curry",
    garnish: "Thai basil",
    servings: 4,
    ingredients: [
      { name: "Chicken thigh, sliced", quantity: 600, unit: "g" },
      { name: "Green curry paste", quantity: 3, unit: "tbsp" },
      { name: "Coconut milk", quantity: 400, unit: "ml" },
      { name: "Fish sauce", quantity: 2, unit: "tbsp" },
      { name: "Palm sugar", quantity: 1, unit: "tbsp" },
      { name: "Thai eggplant", quantity: 150, unit: "g" },
      { name: "Bamboo shoots", quantity: 100, unit: "g" },
      { name: "Thai basil leaves", quantity: 1, unit: "handful" },
      { name: "Red chili, sliced", quantity: 1, unit: "" },
    ],
    steps: [
      { text: "Fry the curry paste in a splash of coconut milk until fragrant.", timerMinutes: 3 },
      { text: "Add the chicken and cook until sealed.", timerMinutes: 4 },
      { text: "Pour in the remaining coconut milk and stir in the fish sauce and palm sugar.", timerMinutes: null },
      { text: "Add the eggplant and bamboo shoots, then simmer until the chicken is cooked through.", timerMinutes: 12 },
      { text: "Stir in the Thai basil off the heat.", timerMinutes: null },
      { text: "Garnish with sliced chili and serve over rice.", timerMinutes: null },
    ],
    source: {
      name: "Abracadish community recipe",
      url: null,
      license: "original",
      author: "Abracadish",
      dateAdded: "2026-08-23",
    },
  },
  {
    id: "beef-tacos",
    title: "Beef Tacos",
    matchType: "likely",
    cuisine: "Mexican",
    protein: "Beef",
    sauce: "Spiced tomato",
    garnish: "Cilantro and lime",
    servings: 4,
    ingredients: [
      { name: "Ground beef", quantity: 500, unit: "g" },
      { name: "Onion, diced", quantity: 1, unit: "" },
      { name: "Garlic, minced", quantity: 2, unit: "cloves" },
      { name: "Chili powder", quantity: 1, unit: "tbsp" },
      { name: "Cumin", quantity: 1, unit: "tsp" },
      { name: "Smoked paprika", quantity: 1, unit: "tsp" },
      { name: "Tomato paste", quantity: 1, unit: "tbsp" },
      { name: "Corn tortillas", quantity: 8, unit: "" },
      { name: "Shredded lettuce", quantity: 1, unit: "handful" },
      { name: "Tomato, diced", quantity: 1, unit: "" },
      { name: "Shredded cheese", quantity: 80, unit: "g" },
      { name: "Cilantro", quantity: 2, unit: "tbsp" },
      { name: "Lime wedges", quantity: 4, unit: "" },
    ],
    steps: [
      { text: "Soften the onion and garlic in a hot pan.", timerMinutes: 4 },
      { text: "Add the ground beef and brown, breaking it up as it cooks.", timerMinutes: 8 },
      { text: "Stir in the chili powder, cumin, paprika, and tomato paste, then simmer.", timerMinutes: 5 },
      { text: "Warm the tortillas.", timerMinutes: null },
      { text: "Fill the tortillas with the beef.", timerMinutes: null },
      { text: "Top with lettuce, tomato, and cheese.", timerMinutes: null },
      { text: "Finish with cilantro and a squeeze of lime.", timerMinutes: null },
    ],
    source: {
      name: "Abracadish community recipe",
      url: null,
      license: "original",
      author: "Abracadish",
      dateAdded: "2026-08-23",
    },
  },
  {
    id: "chicken-fajitas",
    title: "Chicken Fajitas",
    matchType: "likely",
    cuisine: "Mexican",
    protein: "Chicken",
    sauce: "Lime-spiced",
    garnish: "Sour cream",
    servings: 4,
    ingredients: [
      { name: "Chicken breast, sliced", quantity: 600, unit: "g" },
      { name: "Bell peppers, sliced", quantity: 3, unit: "" },
      { name: "Onion, sliced", quantity: 1, unit: "" },
      { name: "Fajita seasoning", quantity: 2, unit: "tbsp" },
      { name: "Lime juice", quantity: 2, unit: "tbsp" },
      { name: "Olive oil", quantity: 2, unit: "tbsp" },
      { name: "Flour tortillas", quantity: 8, unit: "" },
      { name: "Sour cream", quantity: 4, unit: "tbsp" },
      { name: "Guacamole", quantity: 4, unit: "tbsp" },
    ],
    steps: [
      { text: "Toss the chicken with fajita seasoning and lime juice.", timerMinutes: null },
      { text: "Sear the chicken in a hot skillet until browned, then set aside.", timerMinutes: 6 },
      { text: "Sauté the peppers and onion in the same skillet until charred at the edges.", timerMinutes: 6 },
      { text: "Return the chicken to the skillet and toss together.", timerMinutes: null },
      { text: "Warm the tortillas.", timerMinutes: null },
      { text: "Serve the chicken and peppers in tortillas with sour cream and guacamole.", timerMinutes: null },
    ],
    source: {
      name: "Abracadish community recipe",
      url: null,
      license: "original",
      author: "Abracadish",
      dateAdded: "2026-08-23",
    },
  },
  {
    id: "chicken-teriyaki",
    title: "Chicken Teriyaki",
    matchType: "likely",
    cuisine: "Japanese",
    protein: "Chicken",
    sauce: "Sweet soy",
    garnish: "Sesame seeds",
    servings: 4,
    ingredients: [
      { name: "Chicken thigh", quantity: 600, unit: "g" },
      { name: "Soy sauce", quantity: 80, unit: "ml" },
      { name: "Mirin", quantity: 60, unit: "ml" },
      { name: "Sake", quantity: 40, unit: "ml" },
      { name: "Sugar", quantity: 2, unit: "tbsp" },
      { name: "Garlic, minced", quantity: 1, unit: "clove" },
      { name: "Ginger, grated", quantity: 1, unit: "tsp" },
      { name: "Sesame seeds", quantity: 1, unit: "tbsp" },
      { name: "Spring onion, sliced", quantity: 2, unit: "" },
    ],
    steps: [
      { text: "Whisk the soy sauce, mirin, sake, sugar, garlic, and ginger into a sauce.", timerMinutes: null },
      { text: "Sear the chicken skin-side down until crisp.", timerMinutes: 6 },
      { text: "Flip and cook through.", timerMinutes: 5 },
      { text: "Pour in the sauce and simmer until glossy and thickened.", timerMinutes: 5 },
      { text: "Slice the chicken and drizzle with the pan sauce.", timerMinutes: null },
      { text: "Garnish with sesame seeds and spring onion.", timerMinutes: null },
    ],
    source: {
      name: "Abracadish community recipe",
      url: null,
      license: "original",
      author: "Abracadish",
      dateAdded: "2026-08-23",
    },
  },
  {
    id: "miso-ramen",
    title: "Miso Ramen",
    matchType: "likely",
    cuisine: "Japanese",
    protein: "Pork",
    sauce: "Miso broth",
    garnish: "Soft-boiled egg",
    servings: 2,
    ingredients: [
      { name: "Ramen noodles", quantity: 2, unit: "portions" },
      { name: "Pork belly, sliced", quantity: 200, unit: "g" },
      { name: "Miso paste", quantity: 3, unit: "tbsp" },
      { name: "Chicken stock", quantity: 1, unit: "l" },
      { name: "Soy sauce", quantity: 1, unit: "tbsp" },
      { name: "Garlic, minced", quantity: 2, unit: "cloves" },
      { name: "Ginger, grated", quantity: 1, unit: "tsp" },
      { name: "Soft-boiled eggs", quantity: 2, unit: "" },
      { name: "Spring onion", quantity: 2, unit: "" },
      { name: "Nori sheets", quantity: 2, unit: "" },
      { name: "Corn kernels", quantity: 4, unit: "tbsp" },
    ],
    steps: [
      { text: "Sear the pork belly slices until browned.", timerMinutes: 5 },
      { text: "Sauté the garlic and ginger, then whisk in the miso paste.", timerMinutes: 2 },
      { text: "Pour in the chicken stock and soy sauce, then simmer.", timerMinutes: 10 },
      { text: "Cook the ramen noodles separately according to the package.", timerMinutes: 4 },
      { text: "Divide the noodles between bowls and ladle over the broth.", timerMinutes: null },
      { text: "Top with pork, halved soft-boiled eggs, spring onion, nori, and corn.", timerMinutes: null },
    ],
    source: {
      name: "Abracadish community recipe",
      url: null,
      license: "original",
      author: "Abracadish",
      dateAdded: "2026-08-23",
    },
  },
  {
    id: "beef-stroganoff",
    title: "Beef Stroganoff",
    matchType: "likely",
    cuisine: "Russian",
    protein: "Beef",
    sauce: "Sour cream",
    garnish: "Parsley",
    servings: 4,
    ingredients: [
      { name: "Beef sirloin, sliced", quantity: 600, unit: "g" },
      { name: "Onion, sliced", quantity: 1, unit: "" },
      { name: "Mushrooms, sliced", quantity: 300, unit: "g" },
      { name: "Garlic, minced", quantity: 2, unit: "cloves" },
      { name: "Sour cream", quantity: 200, unit: "g" },
      { name: "Beef stock", quantity: 200, unit: "ml" },
      { name: "Dijon mustard", quantity: 1, unit: "tbsp" },
      { name: "Butter", quantity: 2, unit: "tbsp" },
      { name: "Flour", quantity: 1, unit: "tbsp" },
      { name: "Egg noodles", quantity: 300, unit: "g" },
    ],
    steps: [
      { text: "Sear the beef strips in butter until browned, then set aside.", timerMinutes: 4 },
      { text: "Sauté the onion and mushrooms until golden.", timerMinutes: 6 },
      { text: "Stir in the garlic and flour, then cook briefly.", timerMinutes: 1 },
      { text: "Deglaze with the beef stock and mustard.", timerMinutes: null },
      { text: "Return the beef and stir in the sour cream, warming through without boiling.", timerMinutes: 3 },
      { text: "Cook the egg noodles separately.", timerMinutes: 8 },
      { text: "Serve the stroganoff over the noodles, garnished with parsley.", timerMinutes: null },
    ],
    source: {
      name: "Abracadish community recipe",
      url: null,
      license: "original",
      author: "Abracadish",
      dateAdded: "2026-08-23",
    },
  },
  {
    id: "shakshuka",
    title: "Shakshuka",
    matchType: "likely",
    cuisine: "Middle Eastern",
    protein: "Eggs",
    sauce: "Spiced tomato",
    garnish: "Feta and parsley",
    servings: 4,
    ingredients: [
      { name: "Eggs", quantity: 6, unit: "" },
      { name: "Crushed tomatoes", quantity: 400, unit: "g" },
      { name: "Onion, diced", quantity: 1, unit: "" },
      { name: "Red bell pepper, diced", quantity: 1, unit: "" },
      { name: "Garlic, minced", quantity: 3, unit: "cloves" },
      { name: "Cumin", quantity: 1, unit: "tsp" },
      { name: "Smoked paprika", quantity: 1, unit: "tsp" },
      { name: "Chili flakes", quantity: 1, unit: "tsp" },
      { name: "Feta, crumbled", quantity: 80, unit: "g" },
      { name: "Parsley", quantity: 2, unit: "tbsp" },
      { name: "Olive oil", quantity: 2, unit: "tbsp" },
    ],
    steps: [
      { text: "Soften the onion and pepper in olive oil.", timerMinutes: 5 },
      { text: "Stir in the garlic, cumin, paprika, and chili flakes.", timerMinutes: 1 },
      { text: "Add the crushed tomatoes and simmer until thickened.", timerMinutes: 10 },
      { text: "Make small wells in the sauce and crack in the eggs.", timerMinutes: null },
      { text: "Cover and cook until the whites are set but the yolks are still soft.", timerMinutes: 6 },
      { text: "Top with crumbled feta and parsley, then serve with bread.", timerMinutes: null },
    ],
    source: {
      name: "Abracadish community recipe",
      url: null,
      license: "original",
      author: "Abracadish",
      dateAdded: "2026-08-23",
    },
  },
  {
    id: "falafel-wrap",
    title: "Falafel Wrap",
    matchType: "likely",
    cuisine: "Middle Eastern",
    protein: "Chickpea",
    sauce: "Tahini",
    garnish: "Pickled vegetables",
    servings: 4,
    ingredients: [
      { name: "Dried chickpeas, soaked overnight", quantity: 300, unit: "g" },
      { name: "Onion, chopped", quantity: 1, unit: "" },
      { name: "Garlic", quantity: 3, unit: "cloves" },
      { name: "Parsley", quantity: 1, unit: "handful" },
      { name: "Cilantro", quantity: 1, unit: "handful" },
      { name: "Cumin", quantity: 1, unit: "tsp" },
      { name: "Coriander", quantity: 1, unit: "tsp" },
      { name: "Flour", quantity: 2, unit: "tbsp" },
      { name: "Baking powder", quantity: 1, unit: "tsp" },
      { name: "Flatbreads", quantity: 4, unit: "" },
      { name: "Tahini sauce", quantity: 4, unit: "tbsp" },
      { name: "Pickled vegetables", quantity: 100, unit: "g" },
      { name: "Tomato and cucumber", quantity: 1, unit: "handful" },
    ],
    steps: [
      { text: "Blend the soaked chickpeas, onion, garlic, herbs, and spices into a coarse paste.", timerMinutes: null },
      { text: "Stir in the flour and baking powder, then rest the mixture.", timerMinutes: 20 },
      { text: "Shape the mixture into small patties.", timerMinutes: null },
      { text: "Fry the falafel until deeply golden and crisp on both sides.", timerMinutes: 8 },
      { text: "Warm the flatbreads.", timerMinutes: null },
      { text: "Fill with falafel, tahini sauce, pickled vegetables, tomato, and cucumber.", timerMinutes: null },
    ],
    source: {
      name: "Abracadish community recipe",
      url: null,
      license: "original",
      author: "Abracadish",
      dateAdded: "2026-08-23",
    },
  },
  {
    id: "greek-moussaka",
    title: "Greek Moussaka",
    matchType: "likely",
    cuisine: "Greek",
    protein: "Beef",
    sauce: "Bechamel",
    garnish: "Oregano",
    servings: 6,
    ingredients: [
      { name: "Eggplant, sliced", quantity: 2, unit: "large" },
      { name: "Ground lamb or beef", quantity: 600, unit: "g" },
      { name: "Onion, diced", quantity: 1, unit: "" },
      { name: "Garlic, minced", quantity: 2, unit: "cloves" },
      { name: "Crushed tomatoes", quantity: 400, unit: "g" },
      { name: "Cinnamon", quantity: 0.5, unit: "tsp" },
      { name: "Potatoes, sliced", quantity: 2, unit: "" },
      { name: "Butter", quantity: 60, unit: "g" },
      { name: "Flour", quantity: 60, unit: "g" },
      { name: "Milk", quantity: 600, unit: "ml" },
      { name: "Egg yolk", quantity: 1, unit: "" },
      { name: "Nutmeg", quantity: 1, unit: "pinch" },
      { name: "Parmesan, grated", quantity: 50, unit: "g" },
    ],
    steps: [
      { text: "Salt and roast the eggplant slices until golden.", timerMinutes: 20 },
      { text: "Brown the ground meat with the onion and garlic.", timerMinutes: 8 },
      { text: "Stir in the crushed tomatoes and cinnamon, then simmer.", timerMinutes: 15 },
      { text: "Layer the roasted potatoes, eggplant, and meat sauce in a baking dish.", timerMinutes: null },
      { text: "Make a bechamel by whisking flour into melted butter, then gradually adding milk until thickened; stir in the egg yolk, nutmeg, and parmesan.", timerMinutes: 8 },
      { text: "Pour the bechamel over the layers.", timerMinutes: null },
      { text: "Bake until golden on top.", timerMinutes: 40 },
      { text: "Rest before slicing and serve with oregano.", timerMinutes: 10 },
    ],
    source: {
      name: "Abracadish community recipe",
      url: null,
      license: "original",
      author: "Abracadish",
      dateAdded: "2026-08-23",
    },
  },
  {
    id: "bulgarian-kavarma",
    title: "Bulgarian Kavarma",
    matchType: "likely",
    cuisine: "Bulgarian",
    protein: "Pork",
    sauce: "Clay-pot stew",
    garnish: "Parsley",
    servings: 4,
    ingredients: [
      { name: "Pork shoulder, cubed", quantity: 600, unit: "g" },
      { name: "Onion, sliced", quantity: 1, unit: "" },
      { name: "Mushrooms, sliced", quantity: 200, unit: "g" },
      { name: "Bell peppers, sliced", quantity: 2, unit: "" },
      { name: "Carrot, sliced", quantity: 1, unit: "" },
      { name: "Garlic, minced", quantity: 2, unit: "cloves" },
      { name: "Paprika", quantity: 1, unit: "tbsp" },
      { name: "Tomato paste", quantity: 2, unit: "tbsp" },
      { name: "White wine", quantity: 100, unit: "ml" },
      { name: "Bay leaf", quantity: 1, unit: "" },
    ],
    steps: [
      { text: "Sear the pork cubes in a hot pot until browned.", timerMinutes: 8 },
      { text: "Add the onion, carrot, and garlic, and soften.", timerMinutes: 5 },
      { text: "Stir in the paprika and tomato paste.", timerMinutes: null },
      { text: "Deglaze with the white wine.", timerMinutes: null },
      { text: "Add the peppers, mushrooms, and bay leaf, then cover and simmer until the pork is tender.", timerMinutes: 45 },
      { text: "Traditionally finished in individual clay pots in the oven for a few minutes.", timerMinutes: 10 },
      { text: "Garnish with parsley and serve.", timerMinutes: null },
    ],
    source: {
      name: "Abracadish community recipe",
      url: null,
      license: "original",
      author: "Abracadish",
      dateAdded: "2026-08-23",
    },
  },
  {
    id: "bulgarian-shopska",
    title: "Shopska Salad",
    matchType: "likely",
    cuisine: "Bulgarian",
    protein: null,
    sauce: "Fresh vinaigrette",
    garnish: "Grated sirene cheese",
    servings: 4,
    ingredients: [
      { name: "Tomatoes, diced", quantity: 4, unit: "" },
      { name: "Cucumber, diced", quantity: 2, unit: "" },
      { name: "Onion, diced", quantity: 0.5, unit: "" },
      { name: "Green pepper, diced", quantity: 1, unit: "" },
      { name: "Sunflower oil", quantity: 2, unit: "tbsp" },
      { name: "Red wine vinegar", quantity: 1, unit: "tbsp" },
      { name: "Sirene (Bulgarian white cheese), grated", quantity: 150, unit: "g" },
      { name: "Parsley", quantity: 1, unit: "tbsp" },
    ],
    steps: [
      { text: "Dice the tomatoes, cucumber, onion, and pepper evenly.", timerMinutes: null },
      { text: "Toss the vegetables together in a bowl.", timerMinutes: null },
      { text: "Dress with the sunflower oil and red wine vinegar.", timerMinutes: null },
      { text: "Divide onto plates and generously grate sirene cheese over the top.", timerMinutes: null },
      { text: "Finish with chopped parsley and serve chilled.", timerMinutes: null },
    ],
    source: {
      name: "Abracadish community recipe",
      url: null,
      license: "original",
      author: "Abracadish",
      dateAdded: "2026-08-23",
    },
  },
  {
    id: "classic-cheeseburger",
    title: "Classic Cheeseburger",
    matchType: "likely",
    cuisine: "American",
    protein: "Beef",
    sauce: "Burger sauce",
    garnish: "Pickles",
    servings: 4,
    ingredients: [
      { name: "Ground beef", quantity: 600, unit: "g" },
      { name: "Burger buns", quantity: 4, unit: "" },
      { name: "Cheddar slices", quantity: 4, unit: "" },
      { name: "Lettuce", quantity: 4, unit: "leaves" },
      { name: "Tomato, sliced", quantity: 1, unit: "" },
      { name: "Pickles", quantity: 8, unit: "slices" },
      { name: "Onion, sliced", quantity: 0.5, unit: "" },
      { name: "Ketchup", quantity: 4, unit: "tbsp" },
      { name: "Mustard", quantity: 2, unit: "tbsp" },
      { name: "Mayonnaise", quantity: 2, unit: "tbsp" },
      { name: "Salt", quantity: 1, unit: "tsp" },
      { name: "Black pepper", quantity: 1, unit: "tsp" },
    ],
    steps: [
      { text: "Shape the ground beef into four patties, seasoning generously with salt and pepper.", timerMinutes: null },
      { text: "Sear the patties in a hot pan or on a grill.", timerMinutes: 6 },
      { text: "Top each patty with a slice of cheddar to melt.", timerMinutes: 1 },
      { text: "Toast the buns.", timerMinutes: 2 },
      { text: "Spread ketchup, mustard, and mayonnaise on the buns.", timerMinutes: null },
      { text: "Build the burger with lettuce, tomato, the patty, onion, and pickles.", timerMinutes: null },
      { text: "Serve immediately.", timerMinutes: null },
    ],
    source: {
      name: "Abracadish community recipe",
      url: null,
      license: "original",
      author: "Abracadish",
      dateAdded: "2026-08-23",
    },
  },
  {
    id: "chili-con-carne",
    title: "Chili Con Carne",
    matchType: "likely",
    cuisine: "Tex-Mex",
    protein: "Beef",
    sauce: "Spiced tomato",
    garnish: "Sour cream",
    servings: 6,
    ingredients: [
      { name: "Ground beef", quantity: 600, unit: "g" },
      { name: "Onion, diced", quantity: 1, unit: "" },
      { name: "Garlic, minced", quantity: 3, unit: "cloves" },
      { name: "Kidney beans", quantity: 400, unit: "g" },
      { name: "Crushed tomatoes", quantity: 400, unit: "g" },
      { name: "Chili powder", quantity: 2, unit: "tbsp" },
      { name: "Cumin", quantity: 1, unit: "tsp" },
      { name: "Smoked paprika", quantity: 1, unit: "tsp" },
      { name: "Beef stock", quantity: 200, unit: "ml" },
      { name: "Sour cream", quantity: 4, unit: "tbsp" },
      { name: "Spring onion", quantity: 2, unit: "" },
    ],
    steps: [
      { text: "Soften the onion and garlic in a large pot.", timerMinutes: 5 },
      { text: "Add the ground beef and brown thoroughly.", timerMinutes: 8 },
      { text: "Stir in the chili powder, cumin, and paprika.", timerMinutes: null },
      { text: "Add the crushed tomatoes, beef stock, and kidney beans.", timerMinutes: null },
      { text: "Simmer uncovered until thickened.", timerMinutes: 40 },
      { text: "Ladle into bowls and top with sour cream and spring onion.", timerMinutes: null },
    ],
    source: {
      name: "Abracadish community recipe",
      url: null,
      license: "original",
      author: "Abracadish",
      dateAdded: "2026-08-23",
    },
  },
  {
    id: "fish-and-chips",
    title: "Fish and Chips",
    matchType: "likely",
    cuisine: "British",
    protein: "Fish",
    sauce: "Tartar sauce",
    garnish: "Malt vinegar",
    servings: 4,
    ingredients: [
      { name: "Cod fillets", quantity: 4, unit: "" },
      { name: "Flour", quantity: 150, unit: "g" },
      { name: "Cornstarch", quantity: 50, unit: "g" },
      { name: "Baking powder", quantity: 1, unit: "tsp" },
      { name: "Cold beer", quantity: 250, unit: "ml" },
      { name: "Potatoes, cut into chips", quantity: 1, unit: "kg" },
      { name: "Vegetable oil, for frying", quantity: 1, unit: "l" },
      { name: "Tartar sauce", quantity: 4, unit: "tbsp" },
      { name: "Malt vinegar", quantity: 2, unit: "tbsp" },
      { name: "Salt", quantity: 1, unit: "tsp" },
    ],
    steps: [
      { text: "Cut the potatoes into thick chips and par-cook them in oil at a lower temperature.", timerMinutes: 6 },
      { text: "Whisk the flour, cornstarch, baking powder, and cold beer into a batter.", timerMinutes: null },
      { text: "Dip the cod fillets in the batter.", timerMinutes: null },
      { text: "Fry the battered fish until golden and crisp.", timerMinutes: 6 },
      { text: "Fry the par-cooked chips a second time at a higher temperature until crisp.", timerMinutes: 5 },
      { text: "Season both with salt.", timerMinutes: null },
      { text: "Serve with tartar sauce and malt vinegar.", timerMinutes: null },
    ],
    source: {
      name: "Abracadish community recipe",
      url: null,
      license: "original",
      author: "Abracadish",
      dateAdded: "2026-08-23",
    },
  },
  {
    id: "seafood-paella",
    title: "Seafood Paella",
    matchType: "likely",
    cuisine: "Spanish",
    protein: "Seafood",
    sauce: "Saffron rice",
    garnish: "Lemon wedges",
    servings: 6,
    ingredients: [
      { name: "Bomba or paella rice", quantity: 400, unit: "g" },
      { name: "Shrimp", quantity: 300, unit: "g" },
      { name: "Mussels", quantity: 300, unit: "g" },
      { name: "Squid, sliced", quantity: 200, unit: "g" },
      { name: "Onion, diced", quantity: 1, unit: "" },
      { name: "Red bell pepper, diced", quantity: 1, unit: "" },
      { name: "Garlic, minced", quantity: 3, unit: "cloves" },
      { name: "Crushed tomatoes", quantity: 200, unit: "g" },
      { name: "Saffron threads", quantity: 1, unit: "pinch" },
      { name: "Fish or seafood stock", quantity: 1, unit: "l" },
      { name: "Olive oil", quantity: 3, unit: "tbsp" },
      { name: "Lemon wedges", quantity: 6, unit: "" },
      { name: "Parsley", quantity: 2, unit: "tbsp" },
    ],
    steps: [
      { text: "Toast the saffron in warm stock and set aside.", timerMinutes: null },
      { text: "Sauté the onion and pepper in olive oil in a wide paella pan.", timerMinutes: 5 },
      { text: "Stir in the garlic and crushed tomatoes, then cook down.", timerMinutes: 5 },
      { text: "Add the rice and stir to coat it in the sofrito.", timerMinutes: 2 },
      { text: "Pour in the saffron stock and simmer without stirring.", timerMinutes: 10 },
      { text: "Nestle the shrimp, mussels, and squid into the rice as it cooks.", timerMinutes: 8 },
      { text: "Cook until the rice is tender and a crust forms on the bottom.", timerMinutes: 18 },
      { text: "Rest briefly, then garnish with lemon and parsley.", timerMinutes: 5 },
    ],
    source: {
      name: "Abracadish community recipe",
      url: null,
      license: "original",
      author: "Abracadish",
      dateAdded: "2026-08-23",
    },
  },
  {
    id: "beef-pho",
    title: "Beef Pho",
    matchType: "likely",
    cuisine: "Vietnamese",
    protein: "Beef",
    sauce: "Aromatic broth",
    garnish: "Herbs and lime",
    servings: 4,
    ingredients: [
      { name: "Beef bones", quantity: 1, unit: "kg" },
      { name: "Beef sirloin, thinly sliced", quantity: 300, unit: "g" },
      { name: "Onion, halved", quantity: 1, unit: "" },
      { name: "Ginger, halved", quantity: 1, unit: "piece" },
      { name: "Star anise", quantity: 3, unit: "" },
      { name: "Cinnamon stick", quantity: 1, unit: "" },
      { name: "Cloves", quantity: 4, unit: "" },
      { name: "Fish sauce", quantity: 3, unit: "tbsp" },
      { name: "Rice noodles", quantity: 300, unit: "g" },
      { name: "Bean sprouts", quantity: 100, unit: "g" },
      { name: "Thai basil", quantity: 1, unit: "handful" },
      { name: "Lime wedges", quantity: 4, unit: "" },
      { name: "Red chili, sliced", quantity: 1, unit: "" },
    ],
    steps: [
      { text: "Char the onion and ginger, then rinse.", timerMinutes: 8 },
      { text: "Simmer the beef bones with the charred onion and ginger for a base broth.", timerMinutes: 30 },
      { text: "Toast the star anise, cinnamon, and cloves, then add them to the broth.", timerMinutes: 2 },
      { text: "Simmer the broth low for several hours, skimming occasionally.", timerMinutes: 180 },
      { text: "Strain the broth and season with fish sauce.", timerMinutes: null },
      { text: "Cook the rice noodles separately.", timerMinutes: 5 },
      { text: "Assemble bowls with noodles and raw sliced beef, then ladle over the boiling broth to cook the beef.", timerMinutes: null },
      { text: "Serve with bean sprouts, Thai basil, lime, and chili.", timerMinutes: null },
    ],
    source: {
      name: "Abracadish community recipe",
      url: null,
      license: "original",
      author: "Abracadish",
      dateAdded: "2026-08-23",
    },
  },
  {
    id: "hungarian-goulash",
    title: "Hungarian Goulash",
    matchType: "likely",
    cuisine: "Hungarian",
    protein: "Beef",
    sauce: "Paprika broth",
    garnish: "Sour cream",
    servings: 6,
    ingredients: [
      { name: "Beef chuck, cubed", quantity: 800, unit: "g" },
      { name: "Onion, diced", quantity: 2, unit: "" },
      { name: "Garlic, minced", quantity: 3, unit: "cloves" },
      { name: "Sweet paprika", quantity: 3, unit: "tbsp" },
      { name: "Caraway seeds", quantity: 1, unit: "tsp" },
      { name: "Bell pepper, diced", quantity: 1, unit: "" },
      { name: "Tomato, diced", quantity: 1, unit: "" },
      { name: "Potatoes, cubed", quantity: 3, unit: "" },
      { name: "Beef stock", quantity: 1, unit: "l" },
      { name: "Sour cream", quantity: 4, unit: "tbsp" },
    ],
    steps: [
      { text: "Soften the onion in a large pot until deeply golden.", timerMinutes: 10 },
      { text: "Off the heat, stir in the paprika to avoid burning it.", timerMinutes: null },
      { text: "Add the beef and garlic, then brown lightly.", timerMinutes: 8 },
      { text: "Stir in the caraway seeds, bell pepper, and tomato.", timerMinutes: null },
      { text: "Pour in the beef stock and simmer until the beef is tender.", timerMinutes: 90 },
      { text: "Add the potatoes and cook until tender.", timerMinutes: 20 },
      { text: "Ladle into bowls and top with sour cream.", timerMinutes: null },
    ],
    source: {
      name: "Abracadish community recipe",
      url: null,
      license: "original",
      author: "Abracadish",
      dateAdded: "2026-08-23",
    },
  },
  {
    id: "chicken-schnitzel",
    title: "Chicken Schnitzel",
    matchType: "likely",
    cuisine: "Austrian",
    protein: "Chicken",
    sauce: null,
    garnish: "Lemon wedges",
    servings: 4,
    ingredients: [
      { name: "Chicken breast fillets", quantity: 4, unit: "" },
      { name: "Flour", quantity: 100, unit: "g" },
      { name: "Eggs", quantity: 2, unit: "" },
      { name: "Breadcrumbs", quantity: 150, unit: "g" },
      { name: "Vegetable oil, for frying", quantity: 200, unit: "ml" },
      { name: "Lemon wedges", quantity: 4, unit: "" },
      { name: "Salt", quantity: 1, unit: "tsp" },
      { name: "Black pepper", quantity: 1, unit: "tsp" },
    ],
    steps: [
      { text: "Pound the chicken breasts to an even thickness.", timerMinutes: null },
      { text: "Season with salt and pepper.", timerMinutes: null },
      { text: "Dredge each fillet in flour, then beaten egg, then breadcrumbs.", timerMinutes: null },
      { text: "Fry in hot oil until golden and crisp on both sides.", timerMinutes: 8 },
      { text: "Drain on paper towels.", timerMinutes: null },
      { text: "Serve with lemon wedges.", timerMinutes: null },
    ],
    source: {
      name: "Abracadish community recipe",
      url: null,
      license: "original",
      author: "Abracadish",
      dateAdded: "2026-08-23",
    },
  },
  {
    id: "red-lentil-dal",
    title: "Red Lentil Dal",
    matchType: "likely",
    cuisine: "Indian",
    protein: null,
    sauce: "Spiced lentil",
    garnish: "Cilantro",
    servings: 4,
    ingredients: [
      { name: "Red lentils", quantity: 300, unit: "g" },
      { name: "Onion, diced", quantity: 1, unit: "" },
      { name: "Garlic, minced", quantity: 3, unit: "cloves" },
      { name: "Ginger, grated", quantity: 1, unit: "tbsp" },
      { name: "Tomato, diced", quantity: 1, unit: "" },
      { name: "Turmeric", quantity: 1, unit: "tsp" },
      { name: "Cumin seeds", quantity: 1, unit: "tsp" },
      { name: "Ghee", quantity: 2, unit: "tbsp" },
      { name: "Vegetable stock", quantity: 800, unit: "ml" },
      { name: "Cilantro", quantity: 2, unit: "tbsp" },
    ],
    steps: [
      { text: "Rinse the lentils until the water runs clear.", timerMinutes: null },
      { text: "Simmer the lentils with turmeric and vegetable stock until soft.", timerMinutes: 20 },
      { text: "Toast the cumin seeds in ghee, then add the onion, garlic, and ginger.", timerMinutes: 5 },
      { text: "Stir in the tomato and cook down.", timerMinutes: 5 },
      { text: "Stir the tempered spices into the cooked lentils.", timerMinutes: null },
      { text: "Simmer briefly to combine.", timerMinutes: 5 },
      { text: "Garnish with cilantro and serve with rice or flatbread.", timerMinutes: null },
    ],
    source: {
      name: "Abracadish community recipe",
      url: null,
      license: "original",
      author: "Abracadish",
      dateAdded: "2026-08-23",
    },
  },
  {
    id: "vegetable-stir-fry",
    title: "Vegetable Stir Fry",
    matchType: "likely",
    cuisine: "Chinese",
    protein: null,
    sauce: "Soy-ginger",
    garnish: "Sesame seeds",
    servings: 4,
    ingredients: [
      { name: "Broccoli florets", quantity: 200, unit: "g" },
      { name: "Carrot, sliced", quantity: 1, unit: "" },
      { name: "Bell pepper, sliced", quantity: 1, unit: "" },
      { name: "Snap peas", quantity: 150, unit: "g" },
      { name: "Garlic, minced", quantity: 3, unit: "cloves" },
      { name: "Ginger, grated", quantity: 1, unit: "tbsp" },
      { name: "Soy sauce", quantity: 3, unit: "tbsp" },
      { name: "Sesame oil", quantity: 1, unit: "tbsp" },
      { name: "Cornstarch", quantity: 1, unit: "tsp" },
      { name: "Vegetable oil", quantity: 2, unit: "tbsp" },
      { name: "Sesame seeds", quantity: 1, unit: "tbsp" },
    ],
    steps: [
      { text: "Whisk the soy sauce, sesame oil, and cornstarch with a splash of water into a sauce.", timerMinutes: null },
      { text: "Heat the vegetable oil in a wok until smoking.", timerMinutes: null },
      { text: "Stir-fry the garlic and ginger briefly.", timerMinutes: 1 },
      { text: "Add the harder vegetables first (carrot, broccoli) and stir-fry.", timerMinutes: 3 },
      { text: "Add the remaining vegetables and stir-fry until crisp-tender.", timerMinutes: 3 },
      { text: "Pour in the sauce and toss until glossy.", timerMinutes: null },
      { text: "Garnish with sesame seeds and serve over rice.", timerMinutes: null },
    ],
    source: {
      name: "Abracadish community recipe",
      url: null,
      license: "original",
      author: "Abracadish",
      dateAdded: "2026-08-23",
    },
  },
];

const EMBEDDING_API_URL =
  "https://generativelanguage.googleapis.com/v1beta/models/gemini-embedding-001:embedContent";

async function embedText(apiKey, text) {
  const response = await fetch(EMBEDDING_API_URL, {
    method: "POST",
    headers: { "Content-Type": "application/json", "x-goog-api-key": apiKey },
    body: JSON.stringify({ content: { parts: [{ text }] }, outputDimensionality: 768 }),
  });
  if (!response.ok) {
    throw new Error(`Embedding request failed (${response.status}): ${await response.text()}`);
  }
  const payload = await response.json();
  return payload.embedding.values;
}

async function main() {
  const geminiKey = process.env.GEMINI_API_KEY;
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!geminiKey || !supabaseUrl || !serviceRoleKey) {
    throw new Error("Missing GEMINI_API_KEY, NEXT_PUBLIC_SUPABASE_URL, or SUPABASE_SERVICE_ROLE_KEY in .env.local");
  }

  const supabase = createClient(supabaseUrl, serviceRoleKey, { auth: { persistSession: false } });

  for (const recipe of RECIPES) {
    process.stdout.write(`Embedding "${recipe.title}"... `);
    const embedding = await embedText(geminiKey, buildRecipeEmbeddingText(recipe));

    const { error } = await supabase.from("recipes").upsert({
      id: recipe.id,
      title: recipe.title,
      cuisine: recipe.cuisine,
      protein: recipe.protein,
      sauce: recipe.sauce,
      garnish: recipe.garnish,
      match_type: recipe.matchType,
      servings: recipe.servings,
      ingredients: recipe.ingredients,
      steps: recipe.steps,
      source: recipe.source,
      embedding,
    });

    if (error) {
      console.log("FAILED");
      throw new Error(`Upsert failed for ${recipe.id}: ${error.message}`);
    }
    console.log("done");
  }

  console.log(`\nSeeded ${RECIPES.length} recipes.`);
}

main().catch((error) => {
  console.error(error.message);
  process.exit(1);
});
